"""empty message

Revision ID: 0c3e7debc18a
Revises: 
Create Date: 2020-11-15 19:28:31.902345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3e7debc18a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('belongs',
    sa.Column('clothing_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clothing_id'], ['clothing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('clothing_id')
    )
    op.create_table('outfit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('top_id', sa.Integer(), nullable=True),
    sa.Column('bottom_id', sa.Integer(), nullable=True),
    sa.Column('shoes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bottom_id'], ['clothing.id'], ),
    sa.ForeignKeyConstraint(['shoes_id'], ['clothing.id'], ),
    sa.ForeignKeyConstraint(['top_id'], ['clothing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('clothing_id', sa.Integer(), nullable=True),
    sa.Column('clothing_name', sa.String(length=100), nullable=True),
    sa.Column('impression', sa.String(length=100), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['clothing_id'], ['clothing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('outfit')
    op.drop_table('belongs')
    # ### end Alembic commands ###
