"""empty message

Revision ID: 4c940809250e
Revises: 
Create Date: 2020-10-29 14:56:47.384233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c940809250e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('primary_color', sa.String(length=100), nullable=True),
    sa.Column('occasion', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('belongs',
    sa.Column('clothing_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['clothing_id'], ['clothing.id'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('clothing_id')
    )
    op.create_table('matches',
    sa.Column('clothing_id1', sa.Integer(), nullable=False),
    sa.Column('clothing_id2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clothing_id1'], ['clothing.id'], ),
    sa.ForeignKeyConstraint(['clothing_id2'], ['clothing.id'], ),
    sa.PrimaryKeyConstraint('clothing_id1', 'clothing_id2')
    )
    op.create_table('outfit',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('top_id', sa.Integer(), nullable=True),
    sa.Column('bottom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bottom_id'], ['clothing.id'], ),
    sa.ForeignKeyConstraint(['top_id'], ['clothing.id'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('name', 'username')
    )
    op.drop_table('cs316')
    op.drop_table('pharaohs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharaohs',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('cs316',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('outfit')
    op.drop_table('matches')
    op.drop_table('belongs')
    op.drop_table('user')
    op.drop_table('clothing')
    # ### end Alembic commands ###
