"""empty message

Revision ID: 91d823374114
Revises: 
Create Date: 2020-11-11 16:04:20.400713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d823374114'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('belongs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('belongs_username_fkey', 'belongs', type_='foreignkey')
    op.create_foreign_key(None, 'belongs', 'user', ['user_id'], ['id'])
    op.drop_column('belongs', 'username')
    op.add_column('clothing', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clothing', 'user', ['user_id'], ['id'])
    op.add_column('matches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matches', 'user', ['user_id'], ['id'])
    op.add_column('outfit', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('outfit_username_fkey', 'outfit', type_='foreignkey')
    op.create_foreign_key(None, 'outfit', 'user', ['user_id'], ['id'])
    op.drop_column('outfit', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfit', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'outfit', type_='foreignkey')
    op.create_foreign_key('outfit_username_fkey', 'outfit', 'user', ['username'], ['username'])
    op.drop_column('outfit', 'user_id')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'user_id')
    op.drop_constraint(None, 'clothing', type_='foreignkey')
    op.drop_column('clothing', 'user_id')
    op.add_column('belongs', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'belongs', type_='foreignkey')
    op.create_foreign_key('belongs_username_fkey', 'belongs', 'user', ['username'], ['username'])
    op.drop_column('belongs', 'user_id')
    # ### end Alembic commands ###
